# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/p930/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/lge/p930/proprietary/lib/liboncrpc.so:obj/lib/liboncrpc.so \
    vendor/lge/p930/proprietary/lib/libnv.so:obj/lib/libnv.so \
    vendor/lge/p930/proprietary/lib/libv8.so:obj/lib/libv8.so \
    vendor/lge/p930/proprietary/lib/libDivxDrm.so:obj/lib/libDivxDrm.so \
    vendor/lge/p930/proprietary/lib/libtime_genoff.so:obj/lib/libtime_genoff.so \
    vendor/lge/p930/proprietary/lib/libdiag.so:obj/lib/libdiag.so \
    vendor/lge/p930/proprietary/lib/libqc-opt.so:obj/lib/libqc-opt.so \
    vendor/lge/p930/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/lge/p930/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/lge/p930/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/lge/p930/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \

## Flash
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/app/oem_install_flash_player_ics.apk:system/app/oem_install_flash_player.apk \
    vendor/lge/p930/proprietary/lib/plugins/com.adobe.flashplayer/libflashplayer.so:system/lib/plugins/com.adobe.flashplayer/libflashplayer.so \
    vendor/lge/p930/proprietary/lib/plugins/com.adobe.flashplayer/libysshared.so:system/lib/plugins/com.adobe.flashplayer/libysshared.so \
    vendor/lge/p930/proprietary/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so \
    vendor/lge/p930/proprietary/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so \

## Firmware
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    vendor/lge/p930/proprietary/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    vendor/lge/p930/proprietary/etc/firmware/fw_bcmdhd_p2p.bin:system/etc/firmware/fw_bcmdhd_p2p.bin \
    vendor/lge/p930/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/lge/p930/proprietary/etc/firmware/BCM4330B14.hcd:system/etc/firmware/BCM4330B14.hcd \

## RIL, modem, Q6
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/p930/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/p930/proprietary/bin/rild:system/bin/rild \
    vendor/lge/p930/proprietary/bin/qcks:system/bin/qcks \
    vendor/lge/p930/proprietary/bin/ks:system/bin/ks \
    vendor/lge/p930/proprietary/bin/qrngd:system/bin/qrngd \
    vendor/lge/p930/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/lge/p930/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/lge/p930/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/lge/p930/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/p930/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/p930/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/lge/p930/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/p930/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/p930/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/lge/p930/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/lge/p930/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/p930/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/lge/p930/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/lge/p930/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/lge/p930/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/lge/p930/proprietary/lib/libtime_remote_atom.so:system/lib/libtime_remote_atom.so \
    vendor/lge/p930/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/lge/p930/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/lge/p930/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \

## GPS
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/p930/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/lge/p930/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/p930/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/lge/p930/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/p930/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
#    vendor/lge/p930/proprietary/lib/librpc.so:system/lib/librpc.so \
#    vendor/lge/p930/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
#    vendor/lge/p930/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \

## CPU management
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/bin/qosmgr:system/bin/qosmgr \
    vendor/lge/p930/proprietary/bin/thermald:system/bin/thermald \
    vendor/lge/p930/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/lge/p930/proprietary/lib/libthermal_mitigation_fusion.so:system/lib/libthermal_mitigation_fusion.so \
    vendor/lge/p930/proprietary/lib/libthermal_mitigation.so:system/lib/libthermal_mitigation.so \
    vendor/lge/p930/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \

## Audio
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/lge/p930/proprietary/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
    vendor/lge/p930/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/lge/p930/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \

## Camera
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/lib/hw/camera.msm8660.so:system/lib/hw/camera.msm8660.so \
    vendor/lge/p930/proprietary/lib/libOlaFaceDetector.so:system/lib/libOlaFaceDetector.so \
    vendor/lge/p930/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
    vendor/lge/p930/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/p930/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/p930/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
    vendor/lge/p930/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/lge/p930/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
    vendor/lge/p930/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/lge/p930/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/lge/p930/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/lge/p930/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/lge/p930/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/lge/p930/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/lge/p930/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/lge/p930/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/lge/p930/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/lge/p930/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/lge/p930/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/lge/p930/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/lge/p930/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/p930/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/lge/p930/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \

# libchromatix proprietary libs
PRODUCT_COPY_FILES += $(shell find vendor/lge/p930/proprietary/lib/libchromatix -name '*.so' \
	-printf '%p:system/lib/%f ')

## Sensors
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/lib/hw/sensors.msm8660.so:system/lib/hw/sensors.msm8660.so \
    vendor/lge/p930/proprietary/bin/ami304d:system/bin/ami304d \

## OMX
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/lge/p930/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    vendor/lge/p930/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/lge/p930/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/lge/p930/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/lge/p930/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/lge/p930/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/lge/p930/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/lge/p930/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \

## Qcom
PRODUCT_COPY_FILES += \
    vendor/lge/p930/proprietary/lib/libv8.so:system/lib/libv8.so \
    vendor/lge/p930/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/lge/p930/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/lge/p930/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/lge/p930/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \

# use all present proprietary apk
PRODUCT_COPY_FILES += $(shell find vendor/lge/p930/proprietary/gapps -name '*.apk' \
	-printf '%p:system/priv-app/%f ')

# use all present proprietary lib
PRODUCT_COPY_FILES += $(shell find vendor/lge/p930/proprietary/gapps -name '*.so' \
	-printf '%p:system/lib/%f ')

# use all present proprietary jar
PRODUCT_COPY_FILES += $(shell find vendor/lge/p930/proprietary/gapps -name '*.jar' \
	-printf '%p:system/framework/%f ')

# use all present proprietary xml (permissions)
PRODUCT_COPY_FILES += $(shell find vendor/lge/p930/proprietary/gapps -name '*.xml' \
	-printf '%p:system/etc/permissions/%f ')

